image:
        name: cameronnemo/gitlab-ci-startup
        entrypoint: [""]

stages:
        - lint
        - build-test

before_script:
        - xbps-install -S
        - xbps-install -yu xbps
        - xbps-install -yu

cppcheck:
        stage: lint
        script: cppcheck --inline-suppr --error-exitcode=3 .
        except:
                refs:
                        - deb-packaging

autotools:
        stage: build-test
        except:
                refs:
                        - deb-packaging
        script:
                - useradd -d /var/empty -M -U gitlab-ci-startup
                - chown -R gitlab-ci-startup:gitlab-ci-startup ..
                - |
                        runuser -u gitlab-ci-startup -g gitlab-ci-startup -- sh -e -x << EOS
                        autoreconf -fi
                        mkdir build
                        cd build
                        ../configure CFLAGS='-Wall -Werror'
                        make
                        make check CFLAGS=''
                        EOS
