image:
        name: cameronnemo/gitlab-ci-startup
        entrypoint: [""]

stages:
        - lint
        - build-test

before_script:
        - xbps-install -Syu

cppcheck:
        stage: lint
        script: cppcheck --inline-suppr --error-exitcode=3 .

autotools:
        stage: build-test
        script:
                - useradd -d /var/empty -M -U gitlab-ci-startup
                - chown -R gitlab-ci-startup:gitlab-ci-startup ..
                - |
                        runuser -u gitlab-ci-startup -g gitlab-ci-startup -- sh -e -x << EOS
                        test ! -d startup || cd startup
                        autoreconf -fi
                        ./configure
                        make
                        make check
                        EOS
