image:
        name: cameronnemo/gitlab-ci-startup
        entrypoint: [""]

stages:
        - lint
        - build-test

before_script:
        - xbps-install -Syu
        - xbps-install -yu

cppcheck:
        stage: lint
        script: cppcheck --inline-suppr --error-exitcode=3 .
        except:
                refs:
                        - deb-packaging

autotools:
        stage: build-test
        except:
                refs:
                        - deb-packaging
        script:
                - useradd -d /var/empty -M -U gitlab-ci-startup
                - chown -R gitlab-ci-startup:gitlab-ci-startup ..
                - |
                        runuser -u gitlab-ci-startup -g gitlab-ci-startup -- sh -e -x << EOS
                        autoreconf -fi
                        ./configure
                        export CFLAGS=-coverage
                        export LDFLAGS=-lgcov
                        make
                        make check
                        for dir in util init; do
                                cd "${dir}"
                                find . -maxdepth 1 -name '*.c' ! -name 'org.*.c' ! -name 'com.*.c' -print0 | xargs -0 -ISRC gcov SRC
                                cd ..
                        done
                        EOS
                - xbps-fetch -o codecov.bash https://codecov.io/bash
                - bash ./codecov.bash
