.TH startup-socket-bridge 8 2011-03-08 startup
.\"
.SH NAME
startup-socket-bridge \- Bridge between startup and sockets
.\"
.SH SYNOPSIS
.B startup-socket-bridge
.RI [ OPTIONS ]...
.\"
.SH DESCRIPTION
The
.B startup-socket-bridge
queries the
.BR startup (8)
daemon for all job configurations which
.B start on
or
.B stop on
the socket event. It then waits for an incoming connection on each
specified
.BR socket (7)
and when detected emits the socket event (\fBsocket\-event\fP (7)),
setting a number of environment variables for the job to query.
.\"
.SH OPTIONS
.\"
.TP
.B \-\-readyfd
Write a newline into the file descriptor described by the environment
variable READY_FD to indicate readiness.
.\"
.SH AUTHOR
Written by Scott James Remnant
.RB < scott@netsplit.com >

Manual page written by James Hunt
.RB < james.hunt@ubuntu.com >
.\"
.SH BUGS
Report bugs at 
.RB < https://gitlab.com/chinstrap/startup/startup/issues >
.\"
.SH COPYRIGHT
Copyright \(co 2011 Canonical Ltd.
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\"
.SH SEE ALSO
.BR startup (5)
.BR startup (8)
.BR socket (2)
.BR socket (7)
.BR socket\-event (7)
